### PR TITLE
Add gerber_ro_order

### PR DESCRIPTION
**Pull request by asukiaaa**

### CODE REVIEW

**Review by joaoantoniocardoso — APPROVED** [review]

**Comment by asukiaaa** [comment]
https://github.com/devbisme/kicad-3rd-party-tools/pull/67 is merged but this PR  is not.
What pending this?

**Comment by joaoantoniocardoso** [comment]
Only @devbisme has permission to do the merge, I can't help more than just reviewing. Managing repositories takes time, I'm sure he will take a look as soon as possible, as he always does.

**Comment by devbisme** [comment]
Thanks for your addition! Can you please move your entry to the bottom of the **Manufacturing Output Tools** section and resubmit the PR? (New entries always go at the bottom of the appropriate section.)

**Comment by asukiaaa** [comment]
Thank you for checking.
I miss understood that it is alphabet order.
I updated my commit.

**Comment by devbisme** [comment]
Thanks!

**Comment by asukiaaa** [comment]
Thank you for merging :)

**Pull request merged**
